apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysqldb
spec:
  secretName: mypwds
  tlsUseSelfSigned: true
  instances: 3
  # version: '5.7.38'
  # version: '8.0.29'
  router:
    instances: 1
    # version: '8.0.29'
