apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: kamailio-pods
---
# which generate it with following cmd
# k create role kamailio-service-viewer --verb=get --verb=watch \
#   --resource=service --resource-name=kamailio --dry-run=client -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: kamailio-service-viewer
  namespace: default
rules:
- apiGroups:
  - ""
  resourceNames:
  - kamailio
  resources:
  - services
  verbs:
  - get
  - watch
--- 

# create this role binding with following cmd
# k create rolebinding kamailio-service-rolebinding --role=kamailio-service-viewer \
#   --serviceaccount=default:kamailio-pods  --dry-run=client -o yaml -n default
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: kamailio-service-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kamailio-service-viewer
subjects:
- kind: ServiceAccount
  name: kamailio-pods
  namespace: default

---
apiVersion: v1
kind: Service
metadata:
  name: kamailio
  labels:
    app: kamailio
spec:
  type: LoadBalancer
  selector:
    app: kamailio
  ports:
    - name: sip
      protocol: UDP
      port: 5060
      targetPort: 5060

---
apiVersion: v1
kind: Service
metadata:
  name: kamailio-headless
  labels:
    app: kamailio
spec:
  type: LoadBalancer
  selector:
    app: kamailio
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamailio-deployment
  labels:
    app: kamailio
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kamailio
  template:
    metadata:
      labels:
        app: kamailio
    spec:
      serviceAccountName: kamailio-pods
      volumes:
        - name: rtpengine-config
          emptyDir: {}
        - name: kamailio-config
          configMap:
            name: kamailio-config
      initContainers:
        - name: init-rtpengine-config
          image: tutum/dnsutils
          command: ["/bin/sh"]
          args:
            - '-c'
            - >-
               printf '#!trydef DBURL "mysql://kamailio:kamailiorw@mysqldb/kamailio"\n' > /data/rtpengine/db_url.k;
          volumeMounts:
            - name: rtpengine-config
              mountPath: /data/rtpengine
      containers:
      - name: kamailio
        # image: efficacy38/kamailio:v1.13
        image: efficacy38/kamailio:v1.14
        # imagePullPolicy: Always
        # command: ["sleep", "infinity"]
        ports:
        - containerPort: 5060
        volumeMounts:
          - name: rtpengine-config
            mountPath: /data/rtpengine
          - name: kamailio-config
            mountPath: /etc/kamailio

            # - name: ambassador
            #   image: efficacy38/kubectl-proxy:v2
